robots:
  - name: robot0
    center_x: 244
    center_y: 0
    orientation: 0
    type: 'large_robot'
  - name: robot1
    center_x: 550
    center_y: 800
    orientation: -255
    type: 'large_robot'

board_height: 1273
board_width: 1273
board_color: (59, 60, 54)
obstacles:
  border:
    depth: 30
    color: (255, 255, 255)
    outer_spacing: 23
    type: 'border'

  lake_blue:
    border_width: 29
    inner_radius: 38
    color: (58, 166, 221)
    x: 137
    y: 922
    type: 'lake'

  lake_green:
    border_width: 29
    inner_radius: 38
    color: (252, 227, 3)
    x: 1052
    y: 567
    type: 'lake'

  lake_red:
    border_width: 29
    inner_radius: 38
    color: (201, 45, 57)
    x: 397
    y: 232
    type: 'lake'

  rock1:
    x: 825
    y: 1050
    width: 150
    height: 60
    color: (169, 169, 169)
    angle: 10
    type: 'rock'
    movable: False

  rock2:
    x: 975
    y: 275
    width: 300
    height: 90
    color: (169, 169, 169)
    angle: 130
    type: 'rock'
    movable: True