board_height: 841
board_width: 1189
board_color: 235, 235, 235
robots:
  - name: robot0
    center_x: 250
    center_y: 300
    orientation: 0
    type: 'small_robot'
  - name: robot1
    center_x: 650
    center_y: 641
    orientation: 180
    type: 'small_robot'
obstacles:
  - name: 'border'
    depth: 30
    color: 59, 60, 54
    outer_spacing: 23
    type: 'border'

  - name: 'lake_blue'
    border_width: 29
    inner_radius: 38
    color: 58, 166, 221
    x: 500
    y: 170
    hole: False
    type: 'lake'

  - name: 'lake_green'
    border_width: 29
    inner_radius: 38
    color: 252, 227, 3
    x: 250
    y: 600
    hole: False
    type: 'lake'

  - name: 'lake_red'
    border_width: 29
    inner_radius: 38
    color: 201, 45, 57
    x: 850
    y: 500
    hole: False
    type: 'lake'

  - name: 'bottle'
    x: 1000
    y: 300
    radius: 40
    color: 85, 107, 47
    type: 'bottle'