board_height: 841
board_width: 1189
board_color: (235, 235, 235)
robots:
  - name: robot0
    center_x: 200
    center_y: 300
    orientation: 0
    parts:
    - name: brick1
      type: brick
      brick: 0
      x_offset: 0
      y_offset: -22.5
    - name: motor-left
      type: motor
      x_offset: -60
      y_offset: 0.01
      brick: 0
      port: 'ev3-ports:outA'
    - name: motor-right
      type: motor
      x_offset: 60
      y_offset: 0.01
      brick: 0
      port: 'ev3-ports:outD'
    - name: color-sensor-center
      type: color_sensor
      x_offset: 0
      y_offset: 81
      brick: 0
      port: 'ev3-ports:in2'
    - name: touch-sensor-left
      type: touch_sensor
      side: left
      x_offset: -75
      y_offset: 102
      brick: 0
      port: 'ev3-ports:in1'
    - name: touch-sensor-right
      type: touch_sensor
      side: right
      x_offset: 75
      y_offset: 102
      brick: 0
      port: 'ev3-ports:in4'
    - name: ultrasonic-sensor-front
      type: ultrasonic_sensor
      x_offset: 0
      y_offset: -91.5
      brick: 0
      port: 'ev3-ports:in3'
obstacles:
  border:
    depth: 30
    color: (59, 60, 54)
    outer_spacing: 23
    type: 'border'

  lake_blue:
    border_width: 29
    inner_radius: 38
    color: (58, 166, 221)
    x: 500
    y: 170
    hole: False
    type: 'lake'

  lake_yellow:
    border_width: 29
    inner_radius: 38
    color: (252, 227, 3)
    x: 250
    y: 600
    hole: False
    type: 'lake'

  lake_red:
    border_width: 29
    inner_radius: 38
    color: (201, 45, 57)
    x: 850
    y: 500
    hole: False
    type: 'lake'

  rock1:
    x: 800
    y: 300
    width: 50
    height: 550
    color: (85, 107, 47)
    angle: 10
    type: 'rock'

  bottle:
    x: 1000
    y: 300
    radius: 40
    color: (85, 107, 47)
    type: 'bottle'